%% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

%% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

%% Find the sum of all the even-valued terms in the sequence which do not exceed four million.


%% LOGIC:
%% number divisible by 3 are 3, 6, 9, 12, .. = 3 * (1, 2, 3, 4...)
%% same is with divisible by 5
%% now n ( n + 1 ) / 2 will give the sum.
%% Naive Ans: 3 x n ( n + 1 ) / 2 + 5 x n ( n + 1 ) / 2
%% where n = 1000/3 in first case and 1000 / 5 - 1 in second (- 1 because all lower than 1000)
%% CATCH: 3 and 5 have common number 15, 30, 45 etc, we have to remove that
%% Ans: 3 x n ( n + 1 ) / 2 + 5 x n ( n + 1 ) / 2 - 15 * 66 * (67) / 2 
%% (66 == 1000 / 15)


-module(p1).

-export([run/0]).

run() ->
    X = trunc(1000/3),     %% not a perfect divisor, so it is less than 1000
    Y = 1000/5 - 1,        %% need to substract 1
    Z = trunc(1000/15),

    Ans = 3 * X * (X + 1) / 2
	+ 5 * Y * (Y + 1) / 2
	- 15 * Z * (Z + 1) / 2,

    io:format("Ans: ~w", [Ans]).
